name: PlayerLog
version: 1.1
main: com.Mooling0602.PlayerLog.LogInterceptor
api-version: 1.13
description: A plugin to intercept messages about player in-game.
author: Mooling0602
commands:
  chatmsg:
    description: 切换聊天日志拦截
    usage: /chatmsg on|off
    permission: playerlog.chatmsg
    permission-message: 你没有权限执行此命令