name: 自动打包插件

on:
  push:
    branches:
      - main  # 触发打包的分支，可以根据需要修改
  pull_request:
    branches:
      - main  # 可以修改为触发的 PR 分支

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: 打包插件
        run: |
          zip -r "BukkitChatManager-v0.2.1.mcdr" bkchat_manager extra/PlayerLog-1.1.jar LICENSE mcdreforged.plugin.json requirements.txt

      - name: 检查构建
        run: |
          tree

      - name: 上传插件
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: |
            BukkitChatManager-*.mcdr