name: 自动打包插件

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: 打包插件
        run: |
          zip -r "BukkitChatManager-v0.3.0.mcdr" bkchat_manager extra/PlayerLog-1.2.jar LICENSE mcdreforged.plugin.json requirements.txt

      - name: 检查构建
        run: |
          tree

      - name: 上传插件
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: |
            BukkitChatManager-*.mcdr